#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTableQ(TableQ instance);
    partial void UpdateTableQ(TableQ instance);
    partial void DeleteTableQ(TableQ instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WpfApplication3.Properties.Settings.Default.Database1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TableQ> TableQs
		{
			get
			{
				return this.GetTable<TableQ>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TableQ")]
	public partial class TableQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Difficult;
		
		private string _Question;
		
		private string _Ans1;
		
		private string _Ans2;
		
		private string _Ans3;
		
		private string _Ans4;
		
		private string _True;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDifficultChanging(int value);
    partial void OnDifficultChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnAns1Changing(string value);
    partial void OnAns1Changed();
    partial void OnAns2Changing(string value);
    partial void OnAns2Changed();
    partial void OnAns3Changing(string value);
    partial void OnAns3Changed();
    partial void OnAns4Changing(string value);
    partial void OnAns4Changed();
    partial void OnTrueChanging(string value);
    partial void OnTrueChanged();
    #endregion
		
		public TableQ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficult", DbType="Int NOT NULL")]
		public int Difficult
		{
			get
			{
				return this._Difficult;
			}
			set
			{
				if ((this._Difficult != value))
				{
					this.OnDifficultChanging(value);
					this.SendPropertyChanging();
					this._Difficult = value;
					this.SendPropertyChanged("Difficult");
					this.OnDifficultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(111) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans1", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Ans1
		{
			get
			{
				return this._Ans1;
			}
			set
			{
				if ((this._Ans1 != value))
				{
					this.OnAns1Changing(value);
					this.SendPropertyChanging();
					this._Ans1 = value;
					this.SendPropertyChanged("Ans1");
					this.OnAns1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans2", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Ans2
		{
			get
			{
				return this._Ans2;
			}
			set
			{
				if ((this._Ans2 != value))
				{
					this.OnAns2Changing(value);
					this.SendPropertyChanging();
					this._Ans2 = value;
					this.SendPropertyChanged("Ans2");
					this.OnAns2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans3", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Ans3
		{
			get
			{
				return this._Ans3;
			}
			set
			{
				if ((this._Ans3 != value))
				{
					this.OnAns3Changing(value);
					this.SendPropertyChanging();
					this._Ans3 = value;
					this.SendPropertyChanged("Ans3");
					this.OnAns3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ans4", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Ans4
		{
			get
			{
				return this._Ans4;
			}
			set
			{
				if ((this._Ans4 != value))
				{
					this.OnAns4Changing(value);
					this.SendPropertyChanging();
					this._Ans4 = value;
					this.SendPropertyChanged("Ans4");
					this.OnAns4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
