<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\source\Database1.mdf;Integrated Security=True" SettingsObjectName="WpfApplication3.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TableQ" Member="TableQs">
    <Type Name="TableQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Difficult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(111) NOT NULL" CanBeNull="false" />
      <Column Name="Ans1" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Ans2" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Ans3" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Ans4" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="True" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>